# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

N = 31 # This is the last index term before 4 million. (Fib(31) = 3524578.
Fib = [1, 2]
for i in range(1, N):
   Fib.append(Fib[i] + Fib[i-1])
print(Fib[N])
print(sum(filter(lambda x: x % 2 == 0, Fib)))